# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f2c8306da495fe634268a150d503b89e04576bedbbe75759f497bf2688bea40de4b8502b9cde94ba8e3058e098883d86d9ce3b15986eec3569cb92a2152863a

test:
  secret_key_base: 6c604740fbe2d79ceea1ade73686d3e1be8afb22f4f0c383cc0278d83b4ebd943fdb171f663809bf24418fe41142024728f4eb26f31f14571b283d6b97fb5896

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
